# Generated by Django 2.1.4 on 2018-12-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accoung',
            new_name='account',
        ),
    ]
