# Generated by Django 2.1.4 on 2019-01-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeployConfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployconfig',
            name='deployPath',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deployconfig',
            name='shell',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deployconfig',
            name='successResponse',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deployconfig',
            name='url',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
