# Generated by Django 2.1.4 on 2019-01-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeployConfig', '0002_auto_20190103_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployconfig',
            name='deployAS',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
