# Generated by Django 2.1.4 on 2019-01-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='server',
        ),
    ]
