# Generated by Django 2.1.4 on 2019-01-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_app_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='warPath',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
