# Generated by Django 2.1.4 on 2019-01-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverId', models.IntegerField()),
                ('applicationId', models.IntegerField()),
                ('dcId', models.IntegerField()),
                ('host', models.CharField(max_length=1000)),
                ('warPath', models.CharField(max_length=1000)),
                ('deployAS', models.CharField(max_length=1000)),
                ('md5val', models.CharField(max_length=1000)),
                ('remark', models.CharField(max_length=1000)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
