# Generated by Django 2.1.4 on 2019-01-11 10:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 10, 2, 31, 662811, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='deployPath',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='shell',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
