# Generated by Django 2.1.4 on 2019-01-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JdFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('module', models.IntegerField()),
                ('moduleId', models.IntegerField()),
                ('uploadTime', models.DateTimeField()),
            ],
        ),
    ]
