# Generated by Django 2.1.4 on 2019-01-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jdfile',
            name='module',
            field=models.CharField(max_length=1000),
        ),
    ]
