# Generated by Django 2.1.4 on 2019-01-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdfile', '0002_auto_20190103_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdfile',
            name='newName',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jdfile',
            name='origin',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
